(function(){
'use strict';
const URL='https://gioxrpaiwogqqtakjpnv.supabase.co';
const KEY='sb_publishable_nJPMS-Z_20ng1aMJmufbmg_gWFFndrC';
const ROLE={admin:'Administrateur',responsable:'Responsable',lecture:'Lecture seule',employe:'Employé'};
const api={profile:null,avatarUrl:null,onlineIds:new Set(),channel:null,client:null,session:null,refresh};
window.NettoProfileUI=api;
function initials(n){return String(n||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function addStyle(){if(document.getElementById('nettoProfileUIStyle'))return;const s=document.createElement('style');s.id='nettoProfileUIStyle';s.textContent=`
.nettoProfileMenuCard{display:grid;grid-template-columns:40px minmax(0,1fr);gap:10px;align-items:center;margin:2px 4px 8px;padding:10px;border-radius:12px;background:linear-gradient(135deg,#fff6f2,#fffaf5);border:1px solid #ffe0d4;cursor:pointer}
.nettoProfileMenuCard:hover{background:#fff0e9}.nettoProfileMenuAvatar{width:40px;height:40px;border-radius:12px;display:grid;place-items:center;background:var(--profile-accent,#ff5a2a);color:#fff;font-size:12px;font-weight:900;background-size:cover!important;background-position:center!important;overflow:hidden;box-shadow:0 4px 12px #0001}
.nettoProfileMenuAvatar.hasPhoto{color:transparent}.nettoProfileMenuText{min-width:0}.nettoProfileMenuText strong{display:block!important;font-size:12px!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nettoProfileMenuText small{display:block!important;margin-top:2px!important;font-size:9px!important;color:#85878d!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nettoProfileMenuStatus{color:#e64a24!important}
:root[data-theme="dark"] .nettoProfileMenuCard{background:#262326;border-color:#49352f}:root[data-theme="dark"] .nettoProfileMenuCard:hover{background:#302521}:root[data-theme="dark"] .nettoProfileMenuText small{color:#aaa!important}
`;document.head.appendChild(s)}
function paint(el,url,name,color){if(!el)return;el.style.setProperty('--profile-accent',color||'#ff5a2a');if(url){el.classList.add('hasPhoto');el.style.backgroundImage='url("'+url.replace(/"/g,'%22')+'")';el.textContent=''}else{el.classList.remove('hasPhoto');el.style.backgroundImage='';el.textContent=initials(name)}}
function injectMenu(){const menu=document.getElementById('nMenu');if(!menu||!api.profile)return;let card=document.getElementById('nettoProfileMenuCard');if(!card){card=document.createElement('div');card.id='nettoProfileMenuCard';card.className='nettoProfileMenuCard';card.onclick=()=>location.href='profile.html';const title=menu.querySelector('.nMenuTitle');if(title)title.insertAdjacentElement('afterend',card);else menu.prepend(card)}const p=api.profile,name=p.display_name||p.email?.split('@')[0]||'Utilisateur',role=ROLE[p.role]||p.role||'Compte',status=(p.status_text||'').trim();card.innerHTML='<div id="nettoProfileMenuAvatar" class="nettoProfileMenuAvatar"></div><div class="nettoProfileMenuText"><strong>'+esc(name)+'</strong><small>'+esc(role)+'</small>'+(status?'<small class="nettoProfileMenuStatus">'+esc(status)+'</small>':'')+'</div>';paint(document.getElementById('nettoProfileMenuAvatar'),api.avatarUrl,name,p.profile_color)}
function updateKnownUI(){const p=api.profile;if(!p)return;const name=p.display_name||p.email?.split('@')[0]||'Utilisateur',role=ROLE[p.role]||p.role||'Compte';['userName','userMenuName'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=name});['userRole','userMenuRole'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=role});['userAvatar','userMenuAvatar'].forEach(id=>paint(document.getElementById(id),api.avatarUrl,name,p.profile_color));const status=document.getElementById('userStatus');if(status)status.textContent=p.status_text||'';injectMenu()}
function syncPresence(){if(!api.channel)return;const state=api.channel.presenceState(),ids=new Set();Object.values(state).flat().forEach(x=>{if(x?.user_id)ids.add(x.user_id)});api.onlineIds=ids;window.dispatchEvent(new CustomEvent('netto:presence',{detail:{ids:[...ids],count:ids.size}}))}
function startPresence(){if(!api.session||api.channel)return;api.channel=api.client.channel('team-presence',{config:{presence:{key:api.session.user.id}}}).on('presence',{event:'sync'},syncPresence).on('presence',{event:'join'},syncPresence).on('presence',{event:'leave'},syncPresence).subscribe(async status=>{if(status==='SUBSCRIBED'){const p=api.profile||{};await api.channel.track({user_id:api.session.user.id,display_name:p.display_name||p.email||'Utilisateur',page:location.pathname,online_at:new Date().toISOString()});syncPresence()}})}
async function refresh(){if(!api.client||!api.session)return null;const {data:p}=await api.client.from('profiles').select('display_name,email,role,avatar_path,status_text,profile_color').eq('id',api.session.user.id).maybeSingle();if(!p)return null;api.profile=p;api.avatarUrl=null;if(p.avatar_path){const {data:a}=await api.client.storage.from('profile-avatars').createSignedUrl(p.avatar_path,3600);api.avatarUrl=a?.signedUrl||null}document.documentElement.style.setProperty('--profile-accent',p.profile_color||'#ff5a2a');updateKnownUI();window.dispatchEvent(new CustomEvent('netto:profile',{detail:{profile:p,avatarUrl:api.avatarUrl}}));return p}
async function init(){addStyle();if(!window.supabase?.createClient)return;api.client=window.supabase.createClient(URL,KEY);const {data:{session}}=await api.client.auth.getSession();if(!session)return;api.session=session;await refresh();startPresence()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();