(function(){
'use strict';
const URL='https://gioxrpaiwogqqtakjpnv.supabase.co';
const KEY='sb_publishable_nJPMS-Z_20ng1aMJmufbmg_gWFFndrC';
const ROLE={admin:'Administrateur',responsable:'Responsable',lecture:'Lecture seule',employe:'Employé'};
const api={profile:null,avatarUrl:null,onlineIds:new Set(),channel:null,client:null,session:null,notifications:[],notifChannel:null,refresh,loadNotifications};
window.NettoProfileUI=api;

const SOUND_DEFS={
 tap:[[520,0,.055,.15,'sine',610]],
 menuOpen:[[330,0,.10,.16,'sine',430],[520,.045,.12,.09,'sine',620]],
 menuClose:[[520,0,.08,.13,'sine',420],[340,.045,.11,.10,'sine',290]],
 navigate:[[420,0,.065,.11,'sine',540],[680,.035,.075,.075,'sine',780]],
 switch:[[390,0,.08,.12,'triangle',650]],
 confirm:[[523.25,0,.13,.14,'sine'],[659.25,.075,.19,.13,'sine']],
 success:[[392,0,.20,.12,'sine'],[493.88,.085,.25,.14,'sine'],[659.25,.19,.34,.13,'sine']],
 loginSuccess:[[329.63,0,.29,.11,'sine'],[415.3,.085,.33,.13,'sine'],[493.88,.18,.39,.14,'sine'],[659.25,.30,.50,.11,'sine']],
 error:[[245,0,.11,.105,'square',218],[196,.115,.18,.095,'square',174]],
 warning:[[392,0,.10,.11,'triangle'],[392,.15,.12,.10,'triangle']],
 notification:[[783.99,0,.13,.105,'sine'],[1046.5,.105,.27,.09,'sine']],
 message:[[659.25,0,.11,.10,'sine'],[880,.085,.20,.09,'sine']],
 delete:[[370,0,.11,.11,'triangle',300],[246.94,.09,.21,.10,'sine',220]],
 logout:[[587.33,0,.19,.11,'sine'],[493.88,.085,.23,.12,'sine'],[392,.18,.31,.11,'sine'],[293.66,.29,.40,.08,'sine']]
};
let soundCtx=null;
function soundEnabled(){try{return localStorage.getItem('nettoSoundEnabled')!=='0'}catch(_){return true}}
function soundVolume(){try{const raw=localStorage.getItem('nettoSoundVolume');if(raw===null)return .72;const v=Number(raw);return Number.isFinite(v)&&v>=0&&v<=1?v:.72}catch(_){return .72}}
function unlockSound(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;soundCtx=soundCtx||new A();if(soundCtx.state==='suspended')soundCtx.resume().catch(()=>{});return soundCtx}catch(_){return null}}
function playSound(name='tap'){if(!soundEnabled())return;const def=SOUND_DEFS[name]||SOUND_DEFS.tap,a=unlockSound();if(!a)return;const run=()=>{try{const now=a.currentTime,master=a.createGain(),filter=a.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(name==='error'?1350:name==='logout'?1750:2400,now);master.gain.setValueAtTime(Math.max(.0001,soundVolume()*.46),now);master.gain.exponentialRampToValueAtTime(.0001,now+Math.max(...def.map(t=>(t[1]||0)+(t[2]||.1)))+.08);filter.connect(master);master.connect(a.destination);def.forEach(t=>{const [freq,delay=0,dur=.1,gain=.1,type='sine',endFreq]=t,o=a.createOscillator(),g=a.createGain(),st=now+delay;o.type=type;o.frequency.setValueAtTime(freq,st);if(endFreq&&endFreq>0)o.frequency.exponentialRampToValueAtTime(endFreq,st+dur);g.gain.setValueAtTime(.0001,st);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),st+Math.min(.035,dur*.3));g.gain.exponentialRampToValueAtTime(.0001,st+dur);o.connect(g);g.connect(filter);o.start(st);o.stop(st+dur+.025)})}catch(_){}};if(a.state==='suspended')a.resume().then(run).catch(()=>{});else run()}
const sounds={play:playSound,unlock:unlockSound,names:Object.freeze(Object.keys(SOUND_DEFS)),isEnabled:soundEnabled,getVolume:soundVolume,setEnabled(v){try{localStorage.setItem('nettoSoundEnabled',v?'1':'0')}catch(_){};window.dispatchEvent(new Event('netto:sound-settings'))},setVolume(v){const n=Math.max(0,Math.min(1,Number(v)||0));try{localStorage.setItem('nettoSoundVolume',String(n))}catch(_){};window.dispatchEvent(new Event('netto:sound-settings'))}};
window.NettoSounds=sounds;
document.addEventListener('pointerdown',()=>sounds.unlock(),{once:true,capture:true});

function initials(n){return String(n||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function roleLabel(r){return ROLE[r]||r||'Compte'}
function addStyle(){
 if(document.getElementById('nettoGlobalUIStyle'))return;
 const s=document.createElement('style');s.id='nettoGlobalUIStyle';s.textContent=`
 #nMenu,.brandMenu,.nMenuWrap>#nMenu{display:none!important}
 .mobileNavBackdrop{display:none!important}
 .userMenuWrap{display:none!important}
 .nettoGlobalTools{display:flex;align-items:center;gap:8px;margin-left:auto;position:relative;z-index:1300;flex:none}
 .nettoBackBtn{height:42px;border:1px solid #dfe1e5;border-radius:12px;background:#fff;color:#2d3035;display:inline-flex;align-items:center;gap:7px;padding:0 12px;font-size:10px;font-weight:850;cursor:pointer;box-shadow:0 5px 15px #0000000b;flex:none;transition:transform .15s ease,background .15s ease,border-color .15s ease}.nettoBackBtn:hover{background:#f6f7f8;border-color:#cfd2d7}.nettoBackBtn:active{transform:scale(.96)}.nettoBackBtn .nettoBackArrow{font-size:18px;line-height:1}.nettoLegacyBackHidden{display:none!important}
 @media(max-width:650px){.nettoBackBtn{width:42px;padding:0;justify-content:center;border-radius:13px}.nettoBackBtn .nettoBackLabel{display:none}.nettoBackBtn .nettoBackArrow{font-size:20px}}

 .nettoBellWrap,.nettoUserWrap{position:relative}
 .nettoBellBtn{width:42px;height:42px;border:1px solid #e0e2e6;border-radius:13px;background:#fff;display:grid;place-items:center;cursor:pointer;position:relative;box-shadow:0 5px 15px #0000000b}
 .nettoBellBtn svg{width:21px;height:21px;fill:#3d3f44}.nettoNotifBadge{position:absolute;right:-4px;top:-5px;min-width:19px;height:19px;padding:0 5px;border-radius:999px;background:#ff2438;color:#fff;border:2px solid #fff;display:grid;place-items:center;font-size:9px;font-weight:950;line-height:1}
 .nettoNotifBadge.hidden{display:none!important}
 .nettoUserBtn{height:42px;min-width:142px;max-width:220px;border:1px solid #e0e2e6;border-radius:13px;background:#fff;display:grid;grid-template-columns:30px minmax(0,1fr) 14px;align-items:center;gap:7px;padding:5px 8px;cursor:pointer;box-shadow:0 5px 15px #0000000b;text-align:left}
 .nettoTopAvatar{width:30px;height:30px;border-radius:10px;display:grid;place-items:center;background:var(--profile-accent,#ff5a2a);color:#fff;font-size:10px;font-weight:950;background-size:cover!important;background-position:center!important;overflow:hidden}.nettoTopAvatar.hasPhoto{color:transparent}
 .nettoUserText{min-width:0}.nettoUserText strong{display:block;font-size:10.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nettoUserText small{display:block;font-size:8px;color:#868a91;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nettoChevron{font-size:12px;color:#8b8e94}
 .nettoDrop{position:absolute;right:0;top:49px;width:290px;background:#fffffff8;border:1px solid #dfe1e5;border-radius:16px;box-shadow:0 20px 55px #0000002b;backdrop-filter:blur(18px);padding:8px;z-index:3000}.nettoDrop.hidden{display:none!important}
 .nettoUserHead{display:grid;grid-template-columns:40px minmax(0,1fr);gap:9px;align-items:center;padding:9px 10px 10px;border-bottom:1px solid #eceef1;margin-bottom:5px}.nettoUserHead .nettoTopAvatar{width:40px;height:40px;border-radius:12px}.nettoUserHead strong{display:block;font-size:12px}.nettoUserHead small{display:block;color:#8b8e94;font-size:9px;margin-top:2px}
 .nettoNavBtn{width:100%;display:grid;grid-template-columns:34px minmax(0,1fr);gap:9px;align-items:center;text-align:left;border:0;background:transparent;border-radius:11px;padding:8px 9px;cursor:pointer}.nettoNavBtn:hover{background:#f4f5f7}.nettoNavBtn>span:first-child{width:32px;height:32px;border-radius:9px;background:#f0f1f3;display:grid;place-items:center;color:#e54726;font-weight:850;overflow:hidden}.nettoNavBtn>span:first-child img{width:100%;height:100%;display:block;object-fit:cover}.nettoNavBtn strong{display:block;font-size:11px}.nettoNavBtn small{display:block;font-size:8.5px;color:#8b8e94;margin-top:1px}.nettoLogout{margin-top:5px;border-top:1px solid #eceef1;border-radius:0 0 10px 10px;color:#a52218}
 .nettoNotifDrop{width:min(390px,calc(100vw - 20px));padding:0;overflow:hidden}.nettoNotifHead{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:12px 13px;border-bottom:1px solid #eceef1}.nettoNotifHead strong{font-size:12px}.nettoNotifHeadActions{display:flex;gap:5px}.nettoNotifHead button{border:0;background:#f0f1f3;border-radius:8px;padding:6px 7px;font-size:8px;font-weight:800;cursor:pointer}.nettoNotifList{max-height:430px;overflow:auto;padding:7px}.nettoNotifEmpty{padding:28px 12px;text-align:center;color:#999;font-size:10px}
 .nettoNotifItem{display:grid;grid-template-columns:34px minmax(0,1fr) 26px;gap:8px;align-items:start;padding:9px;border-radius:11px;border:1px solid transparent;cursor:pointer;margin-bottom:6px}.nettoNotifItem:last-child{margin-bottom:0}.nettoNotifItem.unread{box-shadow:0 4px 13px #00000008}.nettoNotifIcon{width:32px;height:32px;border-radius:9px;display:grid;place-items:center;font-weight:950}.nettoNotifBody{min-width:0}.nettoNotifBody strong{display:block;font-size:10.5px;line-height:1.25}.nettoNotifBody span{display:block;font-size:9px;line-height:1.35;color:#666;margin-top:2px}.nettoNotifBody small{display:block;font-size:8px;color:#999;margin-top:4px}.nettoNotifDelete{width:25px;height:25px;border:0;border-radius:8px;background:#ffffffaa;color:#999;cursor:pointer;font-size:15px;line-height:1}.nettoNotifDelete:hover{background:#fff0ee;color:#b52c20}
 .nettoNotifItem.manual_edit{background:#f2f6ff;border-color:#dce6fb}.nettoNotifItem.manual_edit .nettoNotifIcon{background:#e2ebff;color:#335fba}.nettoNotifItem.import_new{background:#eff9f2;border-color:#d5eedc}.nettoNotifItem.import_new .nettoNotifIcon{background:#dff3e5;color:#188443}.nettoNotifItem.import_replace{background:#fff6ea;border-color:#ffe0b5}.nettoNotifItem.import_replace .nettoNotifIcon{background:#ffead0;color:#c96a00}.nettoNotifItem.reset_day,.nettoNotifItem.reset_week{background:#fff1ef;border-color:#ffd8d1}.nettoNotifItem.reset_day .nettoNotifIcon,.nettoNotifItem.reset_week .nettoNotifIcon{background:#ffe1dc;color:#bd3022}
 :root[data-theme="dark"] .nettoBackBtn{background:#24272a;border-color:#3b3f44;color:#f1eeea;box-shadow:0 5px 16px #0003}:root[data-theme="dark"] .nettoBackBtn:hover{background:#2c2f33;border-color:#4d5157}
 :root[data-theme="dark"] .nettoBellBtn,:root[data-theme="dark"] .nettoUserBtn{background:#202225;border-color:#383c41;color:#f5f2ef;box-shadow:0 6px 18px #0003}:root[data-theme="dark"] .nettoBellBtn:hover,:root[data-theme="dark"] .nettoUserBtn:hover{background:#272a2d;border-color:#4b403b}:root[data-theme="dark"] .nettoBellBtn svg{fill:#e9e6e2}:root[data-theme="dark"] .nettoNotifBadge{border-color:#202225}:root[data-theme="dark"] .nettoDrop{background:#1b1d20fa;border-color:#3a3e43;color:#f5f2ef;box-shadow:0 24px 70px #0008}:root[data-theme="dark"] .nettoNavBtn:hover{background:#272a2d}:root[data-theme="dark"] .nettoNavBtn>span:first-child{background:#30241f;color:#ff9a72}:root[data-theme="dark"] .nettoNotifHead,:root[data-theme="dark"] .nettoUserHead{background:linear-gradient(180deg,#1f2124,#1b1d20);border-color:#34383d}:root[data-theme="dark"] .nettoNotifBody span,:root[data-theme="dark"] .nettoUserText small,:root[data-theme="dark"] .nettoUserHead small{color:#aaa5a0}:root[data-theme="dark"] .nettoNotifItem{border-color:#33373b}:root[data-theme="dark"] .nettoNotifItem.manual_edit{background:#1c2637;border-color:#314568}:root[data-theme="dark"] .nettoNotifItem.import_new{background:#183025;border-color:#2d503b}:root[data-theme="dark"] .nettoNotifItem.import_replace{background:#342819;border-color:#574225}:root[data-theme="dark"] .nettoNotifItem.reset_day,:root[data-theme="dark"] .nettoNotifItem.reset_week{background:#38221f;border-color:#5a332d}
 @media(max-width:700px){
   header{overflow:visible!important}.nettoGlobalTools{gap:6px}.nettoBellBtn{width:40px;height:40px;border-radius:12px}.nettoUserBtn{height:40px;min-width:105px;max-width:140px;grid-template-columns:28px minmax(0,1fr) 12px;padding:5px 6px}.nettoTopAvatar{width:28px;height:28px}.nettoUserText strong{font-size:9.5px}.nettoUserText small{font-size:7px}
   .nettoDrop{position:fixed!important;right:10px!important;left:10px!important;top:max(62px,calc(env(safe-area-inset-top) + 52px))!important;width:auto!important;max-height:calc(100dvh - 76px)!important;overflow:auto!important;border-radius:18px!important;z-index:5000!important}
   .nettoNotifList{max-height:calc(100dvh - 145px)}.nettoNavBtn{min-height:48px}.nettoNavBtn strong{font-size:11px}.nettoNavBtn small{font-size:8.5px}
   .backBtn,header>.top>.back,header .top>.back{display:none!important}
 }
 @media(max-width:430px){.nettoGlobalTools{gap:5px}.nettoUserBtn{width:38px;min-width:38px;max-width:38px;height:38px;grid-template-columns:28px;padding:5px}.nettoChevron,.nettoUserText{display:none}.nettoBellBtn{width:38px;height:38px}}
 `;document.head.appendChild(s)
}
function paint(el,url,name,color){if(!el)return;el.style.setProperty('--profile-accent',color||'#ff5a2a');if(url){el.classList.add('hasPhoto');el.style.backgroundImage='url("'+url.replace(/"/g,'%22')+'")';el.textContent=''}else{el.classList.remove('hasPhoto');el.style.backgroundImage='';el.textContent=initials(name)}}
function makeButton(icon,title,sub,url,cls=''){return '<button class="nettoNavBtn '+cls+'" data-url="'+esc(url||'')+'"><span>'+icon+'</span><span><strong>'+esc(title)+'</strong><small>'+esc(sub||'')+'</small></span></button>'}
function currentTheme(){return document.documentElement.dataset.theme==='dark'?'dark':'light'}
function changeTheme(){if(typeof window.toggleTheme==='function'){window.toggleTheme({stopPropagation(){}});return}const next=currentTheme()==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('nettoTheme',next)}catch(_){};updateThemeText()}
function updateThemeText(){const dark=currentTheme()==='dark';document.querySelectorAll('.nettoThemeLabel').forEach(x=>x.textContent=dark?'Mode clair':'Mode sombre');document.querySelectorAll('.nettoThemeIcon').forEach(x=>x.textContent=dark?'☀':'☾')}
function bindHomeMark(){
 document.querySelectorAll('.mark,.brandMark,.nMenuBtn,.brandMenuBtn').forEach(b=>{if((b.textContent||'').trim()!=='N')return;b.removeAttribute('onclick');b.removeAttribute('aria-expanded');b.setAttribute('aria-label','Retour à l’accueil');b.onclick=e=>{e.preventDefault();e.stopPropagation();location.href='home.html'}})
 document.querySelectorAll('#nMenu,.brandMenu').forEach(x=>x.classList.add('hidden'))
 document.body.classList.remove('mobileNavOpen')
}
function findHeaderTop(){return document.querySelector('#site header .top')||document.querySelector('header .top')}
function buildGlobalHeader(){
 if(document.getElementById('nettoGlobalTools')||!api.profile)return;bindHomeMark();
 const top=findHeaderTop();if(!top)return;
 const existing=top.querySelector('.userMenuWrap');if(existing)existing.style.display='none';
 const p=api.profile,name=p.display_name||'Utilisateur',role=roleLabel(p.role);
 const wrap=document.createElement('div');wrap.id='nettoGlobalTools';wrap.className='nettoGlobalTools';
 wrap.innerHTML='<div class="nettoBellWrap"><button id="nettoBellBtn" class="nettoBellBtn" aria-label="Notifications" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 22a2.55 2.55 0 0 0 2.45-1.85h-4.9A2.55 2.55 0 0 0 12 22Zm7-5.1-1.75-2.05V9.5A5.26 5.26 0 0 0 13 4.34V3a1 1 0 1 0-2 0v1.34A5.26 5.26 0 0 0 6.75 9.5v5.35L5 16.9V18h14v-1.1Z"/></svg><b id="nettoNotifBadge" class="nettoNotifBadge hidden">0</b></button><div id="nettoNotifDrop" class="nettoDrop nettoNotifDrop hidden"><div class="nettoNotifHead"><strong>Notifications</strong><div class="nettoNotifHeadActions"><button id="nettoMarkRead">Tout lire</button><button id="nettoDeleteAll">Tout supprimer</button></div></div><div id="nettoNotifList" class="nettoNotifList"><div class="nettoNotifEmpty">Chargement…</div></div></div></div><div class="nettoUserWrap"><button id="nettoUserBtn" class="nettoUserBtn" aria-expanded="false"><span id="nettoTopAvatar" class="nettoTopAvatar">U</span><span class="nettoUserText"><strong>'+esc(name)+'</strong><small>'+esc(role)+'</small></span><span class="nettoChevron">⌄</span></button><div id="nettoUserDrop" class="nettoDrop hidden"><div class="nettoUserHead"><span id="nettoMenuAvatar" class="nettoTopAvatar">U</span><span><strong>'+esc(name)+'</strong><small>'+esc(role)+'</small></span></div>'+makeButton('⌂','Accueil','Retour au portail','home.html')+makeButton('☺','Mon profil','Profil et notifications','profile.html')+(p.role==='admin'?makeButton('✦','Défis & Boutique','Missions, boutique et personnalisation','rewards.html'):'')+makeButton('<img src="assets/logo-stock.svg" alt="">','Stock F&L','Gestion du stock','index.html')+makeButton('<img src="assets/logo-planning.svg" alt="">','Planning','Horaires de l’équipe','planning.html')+makeButton('<img src="assets/logo-equipe.svg" alt="">','Équipe','Messagerie interne','chat.html')+makeButton('<img src="assets/logo-article.svg" alt="">','Fiches articles','Référentiel articles','articles.html')+(p.role==='admin'?makeButton('<img src="assets/logo-boulangerie.svg" alt="">','Boulangerie','Stock • Consulter • Gestion','bakery.html')+makeButton('◫','Vue test','Stock groupé par familles','stock-test.html')+makeButton('♙','Gestion des comptes','Utilisateurs, accès et journal','accounts.html')+makeButton('⚙','Personnalisation','Réglages du portail','settings.html'):'')+'<button id="nettoThemeBtn" class="nettoNavBtn"><span class="nettoThemeIcon">☾</span><span><strong class="nettoThemeLabel">Mode sombre</strong><small>Changer l’apparence</small></span></button><button id="nettoLogoutBtn" class="nettoNavBtn nettoLogout"><span>↪</span><span><strong>Déconnexion</strong><small>Quitter la session</small></span></button></div></div>';
 top.appendChild(wrap);
 paint(document.getElementById('nettoTopAvatar'),api.avatarUrl,name,p.profile_color);paint(document.getElementById('nettoMenuAvatar'),api.avatarUrl,name,p.profile_color);updateThemeText();
 wrap.querySelectorAll('.nettoNavBtn[data-url]').forEach(b=>b.onclick=()=>{sounds.play('navigate');const url=b.dataset.url;setTimeout(()=>location.href=url,55)});
 document.getElementById('nettoThemeBtn').onclick=e=>{e.stopPropagation();sounds.play('switch');changeTheme();updateThemeText()};
 document.getElementById('nettoLogoutBtn').onclick=async()=>{sounds.play('logout');await new Promise(r=>setTimeout(r,390));await api.client.auth.signOut();location.href='index.html'};
 document.getElementById('nettoUserBtn').onclick=e=>{e.stopPropagation();toggleDrop('user')};
 document.getElementById('nettoBellBtn').onclick=e=>{e.stopPropagation();toggleDrop('notifications')};
 document.getElementById('nettoMarkRead').onclick=e=>{e.stopPropagation();sounds.play('confirm');markAllRead()};
 document.getElementById('nettoDeleteAll').onclick=e=>{e.stopPropagation();sounds.play('warning');deleteAllNotifications()};
 document.addEventListener('click',e=>{if(!e.target.closest('#nettoGlobalTools'))closeDrops()});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrops()});
}
function toggleDrop(which){const n=document.getElementById('nettoNotifDrop'),u=document.getElementById('nettoUserDrop'),nb=document.getElementById('nettoBellBtn'),ub=document.getElementById('nettoUserBtn');if(which==='notifications'){const open=n.classList.contains('hidden');sounds.play(open?'menuOpen':'menuClose');n.classList.toggle('hidden',!open);u.classList.add('hidden');nb.setAttribute('aria-expanded',String(open));ub.setAttribute('aria-expanded','false');if(open)loadNotifications()}else{const open=u.classList.contains('hidden');sounds.play(open?'menuOpen':'menuClose');u.classList.toggle('hidden',!open);n.classList.add('hidden');ub.setAttribute('aria-expanded',String(open));nb.setAttribute('aria-expanded','false')}}
function closeDrops(){document.getElementById('nettoNotifDrop')?.classList.add('hidden');document.getElementById('nettoUserDrop')?.classList.add('hidden');document.getElementById('nettoBellBtn')?.setAttribute('aria-expanded','false');document.getElementById('nettoUserBtn')?.setAttribute('aria-expanded','false')}
function notificationIcon(k){return k==='import_new'?'▦':k==='import_replace'?'↻':(k==='reset_day'||k==='reset_week')?'⌫':'✎'}
function notificationDate(v){const d=new Date(v);return d.toLocaleDateString('fr-FR')+' à '+d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function renderNotifications(){
 const list=document.getElementById('nettoNotifList'),badge=document.getElementById('nettoNotifBadge');if(!list||!badge)return;const unread=api.notifications.filter(n=>!n.read_at).length;badge.textContent=unread>99?'99+':String(unread);badge.classList.toggle('hidden',unread===0);
 if(!api.notifications.length){list.innerHTML='<div class="nettoNotifEmpty">Aucune notification pour le moment.</div>';return}
 list.innerHTML=api.notifications.map(n=>'<article class="nettoNotifItem '+esc(n.kind)+' '+(!n.read_at?'unread':'')+'" data-id="'+n.id+'" data-url="'+esc(n.target_url||'')+'"><span class="nettoNotifIcon">'+notificationIcon(n.kind)+'</span><div class="nettoNotifBody"><strong>'+esc(n.title)+'</strong><span>'+esc(n.message)+'</span><small>'+notificationDate(n.created_at)+'</small></div><button class="nettoNotifDelete" title="Supprimer" aria-label="Supprimer la notification">×</button></article>').join('');
 list.querySelectorAll('.nettoNotifItem').forEach(el=>{el.onclick=async e=>{if(e.target.closest('.nettoNotifDelete'))return;const id=Number(el.dataset.id),url=el.dataset.url;await markRead(id);if(url)location.href=url}});
 list.querySelectorAll('.nettoNotifDelete').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteNotification(Number(b.closest('.nettoNotifItem').dataset.id))})
}
async function loadNotifications(){if(!api.client||!api.session)return;const {data,error}=await api.client.from('planning_notifications').select('id,kind,title,message,planning_date,week_start,target_url,read_at,created_at').eq('user_id',api.session.user.id).order('created_at',{ascending:false}).limit(80);if(error){console.warn('Notifications:',error);return}api.notifications=data||[];renderNotifications();window.dispatchEvent(new CustomEvent('netto:notifications',{detail:{notifications:api.notifications,unread:api.notifications.filter(n=>!n.read_at).length}}))}
async function markRead(id){const n=api.notifications.find(x=>x.id===id);if(!n||n.read_at)return;const now=new Date().toISOString(),{error}=await api.client.from('planning_notifications').update({read_at:now}).eq('id',id).eq('user_id',api.session.user.id);if(!error){n.read_at=now;renderNotifications()}}
async function markAllRead(){if(!api.notifications.some(n=>!n.read_at))return;const {error}=await api.client.from('planning_notifications').update({read_at:new Date().toISOString()}).eq('user_id',api.session.user.id).is('read_at',null);if(!error)loadNotifications()}
async function deleteNotification(id){const {error}=await api.client.from('planning_notifications').delete().eq('id',id).eq('user_id',api.session.user.id);if(!error){sounds.play('delete');api.notifications=api.notifications.filter(n=>n.id!==id);renderNotifications();window.dispatchEvent(new CustomEvent('netto:notifications',{detail:{notifications:api.notifications,unread:api.notifications.filter(n=>!n.read_at).length}}))}}
async function deleteAllNotifications(){if(!api.notifications.length)return;if(!confirm('Supprimer toutes tes notifications ?'))return;const ids=api.notifications.map(n=>n.id);const {error}=await api.client.from('planning_notifications').delete().eq('user_id',api.session.user.id).in('id',ids);if(!error){sounds.play('delete');api.notifications=[];renderNotifications();window.dispatchEvent(new CustomEvent('netto:notifications',{detail:{notifications:[],unread:0}}))}}
function startNotificationsRealtime(){if(!api.session||api.notifChannel)return;api.notifChannel=api.client.channel('planning-notifications-'+api.session.user.id).on('postgres_changes',{event:'*',schema:'public',table:'planning_notifications',filter:'user_id=eq.'+api.session.user.id},()=>{sounds.play('notification');loadNotifications()}).subscribe()}
function syncPresence(){if(!api.channel)return;const state=api.channel.presenceState(),ids=new Set();Object.values(state).flat().forEach(x=>{if(x?.user_id)ids.add(x.user_id)});api.onlineIds=ids;window.dispatchEvent(new CustomEvent('netto:presence',{detail:{ids:[...ids],count:ids.size}}))}
function startPresence(){if(!api.session||api.channel)return;api.channel=api.client.channel('team-presence',{config:{presence:{key:api.session.user.id}}}).on('presence',{event:'sync'},syncPresence).on('presence',{event:'join'},syncPresence).on('presence',{event:'leave'},syncPresence).subscribe(async status=>{if(status==='SUBSCRIBED'){const p=api.profile||{};await api.channel.track({user_id:api.session.user.id,display_name:p.display_name||'Utilisateur',page:location.pathname,online_at:new Date().toISOString()});syncPresence()}})}
function updateKnownUI(){const p=api.profile;if(!p)return;const name=p.display_name||'Utilisateur',role=roleLabel(p.role);['userName','userMenuName'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=name});['userRole','userMenuRole'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=role});['userAvatar','userMenuAvatar'].forEach(id=>paint(document.getElementById(id),api.avatarUrl,name,p.profile_color));const status=document.getElementById('userStatus');if(status)status.textContent=p.status_text||'';buildGlobalHeader()}
function pageFile(){return (location.pathname.split('/').pop()||'home.html').toLowerCase()}
function backFallback(){return pageFile()==='stock-test.html'?'index.html':'home.html'}
function goBack(){
 sounds.play('navigate');
 const fallback=backFallback();
 let sameOriginRef=false;
 try{sameOriginRef=!!document.referrer&&new URL(document.referrer).origin===location.origin}catch(_){}
 setTimeout(()=>{if(sameOriginRef&&history.length>1)history.back();else location.href=fallback},45)
}
function addBackButton(){
 const p=pageFile();if(p==='home.html'||p==='')return;
 document.querySelectorAll('header .backBtn').forEach(x=>x.classList.add('nettoLegacyBackHidden'));
 if(document.getElementById('nettoGlobalBack'))return;
 const b=document.createElement('button');b.id='nettoGlobalBack';b.type='button';b.className='nettoBackBtn';b.setAttribute('aria-label','Retour');b.innerHTML='<span class="nettoBackArrow">←</span><span class="nettoBackLabel">Retour</span>';b.onclick=goBack;
 const top=document.querySelector('header .top');
 if(top)top.insertBefore(b,top.firstChild);
 else{b.style.position='fixed';b.style.left='12px';b.style.top='12px';b.style.zIndex='3500';document.body.appendChild(b)}
}
function pageArea(){const p=(location.pathname.split('/').pop()||'home.html').toLowerCase();const map={'home.html':'Accueil','index.html':'Stock F&L','planning.html':'Planning','chat.html':'Équipe','profile.html':'Mon profil','articles.html':'Fiches articles','bakery.html':'Boulangerie','settings.html':'Personnalisation du site','stock-test.html':'Vue stock groupée','rewards.html':'Défis & Boutique','accounts.html':'Gestion des comptes'};return map[p]||document.title||'Portail'}
async function logPageView(){if(!api.client||!api.session)return;try{await api.client.rpc('audit_page_view',{p_area:pageArea(),p_path:(location.pathname||'')+(location.search||''),p_title:document.title||pageArea()})}catch(e){console.warn('Journal consultation:',e)}}
async function refresh(){if(!api.client||!api.session)return null;const {data:p}=await api.client.from('profiles').select('display_name,role,avatar_path,status_text,profile_color').eq('id',api.session.user.id).maybeSingle();if(!p)return null;api.profile=p;api.avatarUrl=null;if(p.avatar_path){const {data:a}=await api.client.storage.from('profile-avatars').createSignedUrl(p.avatar_path,3600);api.avatarUrl=a?.signedUrl||null}document.documentElement.style.setProperty('--profile-accent',p.profile_color||'#ff5a2a');updateKnownUI();window.dispatchEvent(new CustomEvent('netto:profile',{detail:{profile:p,avatarUrl:api.avatarUrl}}));return p}
async function init(){addStyle();if(!window.supabase?.createClient)return;api.client=window.supabase.createClient(URL,KEY);const {data:{session}}=await api.client.auth.getSession();if(!session)return;api.session=session;await refresh();addBackButton();logPageView();bindHomeMark();await loadNotifications();startNotificationsRealtime();startPresence();window.addEventListener('focus',loadNotifications);document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadNotifications()})}
const rewardScript=document.createElement('script');rewardScript.src='reward-profile.js?v=2';rewardScript.defer=true;document.head.appendChild(rewardScript);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
