(()=>{'use strict';
let items=[],equipment=[],loading=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function item(uid,kind){const e=equipment.find(e=>e.user_id===uid&&e.kind===kind);return e&&items.find(i=>i.id===e.item_id)}
function paint(el,uid){if(!el)return;const avatar=item(uid,'avatar'),frame=item(uid,'frame'),accessory=item(uid,'accessory'),hasPhoto=!!el.querySelector(':scope > img');el.classList.add('rewardDecorated');if(frame&&/^#[0-9a-f]{6}$/i.test(frame.visual))el.style.setProperty('--reward-frame',frame.visual);else el.style.removeProperty('--reward-frame');let layer=el.querySelector(':scope > .rewardOverlay');if((avatar&&!hasPhoto)||accessory){if(!layer){layer=document.createElement('span');layer.className='rewardOverlay';el.appendChild(layer)}const avatarHtml=avatar&&!hasPhoto?((/^data:image\//.test(avatar.visual||'')||/\.(svg|png|webp|jpe?g)(\?|$)/i.test(avatar.visual||''))?'<img class="rewardFaceImage" src="'+esc(avatar.visual)+'" alt="">':'<span class="rewardFace">'+esc(avatar.visual)+'</span>') :'';const html=avatarHtml+(accessory?'<span class="rewardAccessory">'+esc(accessory.visual)+'</span>':'');if(layer.innerHTML!==html)layer.innerHTML=html}else layer?.remove()}
function title(el,uid){if(!el)return;const t=item(uid,'title');let tag=el.querySelector(':scope > .rewardTitle');if(t){if(!tag){tag=document.createElement('span');tag.className='rewardTitle';el.appendChild(tag)}if(tag.textContent!==t.visual)tag.textContent=t.visual}else tag?.remove()}
function render(){const api=window.NettoProfileUI;if(!api?.session)return;const uid=api.session.user.id;['nettoTopAvatar','nettoMenuAvatar','userAvatar','userMenuAvatar','avatar'].forEach(id=>paint(document.getElementById(id),uid));title(document.querySelector('.nettoUserHead>span:last-child'),uid);title(document.getElementById('displayName')?.parentElement,uid);document.querySelectorAll('[data-reward-user]').forEach(el=>{paint(el.querySelector('.memberAvatar,.avatar'),el.dataset.rewardUser);title(el.querySelector('.memberInfo,.msgTop'),el.dataset.rewardUser)});
const theme=item(uid,'theme');if(theme&&/^#[0-9a-f]{6}$/i.test(theme.visual)){document.documentElement.style.setProperty('--accent',theme.visual);document.documentElement.style.setProperty('--profile-accent',theme.visual);document.documentElement.style.setProperty('--reward-theme',theme.visual)}else{document.documentElement.style.removeProperty('--reward-theme');document.documentElement.style.removeProperty('--accent');document.documentElement.style.setProperty('--profile-accent',api.profile?.profile_color||'#ff5a2a')}
}
async function load(){const api=window.NettoProfileUI;if(!api?.session||loading)return;loading=true;try{const [c,e]=await Promise.all([api.client.from('reward_catalog').select('id,kind,visual'),api.client.from('reward_equipment').select('user_id,kind,item_id')]);if(c.error||e.error)return;items=c.data||[];equipment=e.data||[];render()}finally{loading=false}}
const style=document.createElement('style');style.textContent=`.rewardDecorated{position:relative!important;outline:3px solid var(--reward-frame,transparent);outline-offset:2px;overflow:visible!important}.rewardOverlay{position:absolute;inset:0;pointer-events:none;border-radius:inherit;color:initial;display:block}.rewardFace{position:absolute;inset:0;display:grid;place-items:center;font-size:1.45em;background:var(--reward-theme,#fff2e9);border-radius:inherit;color:#222}.rewardFaceImage{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;border-radius:inherit}.rewardAccessory{position:absolute;right:-5px;bottom:-5px;font-size:14px;line-height:1.1;filter:drop-shadow(0 1px 1px #fff)}.rewardTitle{display:block;font-size:12px!important;font-weight:700;line-height:1.5;color:#bc4c0d;margin-top:3px}.msgTop .rewardTitle{display:inline-block;margin:0 3px;white-space:normal}.nettoUserHead{overflow:visible}header{border-bottom-color:var(--reward-theme)!important}:root[data-theme="dark"] .rewardTitle{color:#ffad7f}`;document.head.appendChild(style);
function start(){let scheduled=false;const observer=new MutationObserver(records=>{if(records.every(r=>r.target.closest?.('.rewardOverlay,.rewardTitle')))return;if(!scheduled){scheduled=true;requestAnimationFrame(()=>{scheduled=false;render()})}});observer.observe(document.body,{childList:true,subtree:true});
window.addEventListener('netto:profile',load);window.addEventListener('netto:rewards',load);window.addEventListener('focus',load);load();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();

