begin;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='admin' limit 1),true);
set local role authenticated;
do $$
declare m uuid; n uuid; c uuid; b integer; before_balance integer; blocked boolean;
begin
 select coalesce((select balance from public.reward_wallets where user_id=auth.uid()),0) into before_balance;
 insert into public.reward_missions(title,instructions,points,created_by) values('TEST rollback','Critères du test',200,auth.uid()) returning id into m;
 insert into public.reward_missions(title,instructions,points,created_by) values('TEST deuxième','Critères du test',10,auth.uid()) returning id into n;
 perform public.reward_mission_action(m,'reserve');
 blocked:=false;begin perform public.reward_mission_action(n,'reserve');exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : deux réservations actives';end if;
 perform public.reward_mission_action(m,'submit','Travail vérifié pendant le test');
 perform public.reward_mission_action(m,'reject','Correction nécessaire');
 if (select status from public.reward_missions where id=m)<>'open' then raise exception 'ÉCHEC : rejet';end if;
 perform public.reward_mission_action(m,'reserve');
 perform public.reward_mission_action(m,'submit','Correction terminée');
 perform public.reward_mission_action(m,'approve');
 blocked:=false;begin perform public.reward_mission_action(m,'approve');exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : double validation';end if;
 if (select balance from public.reward_wallets where user_id=auth.uid())<>before_balance+200 then raise exception 'ÉCHEC : crédit';end if;
 insert into public.reward_catalog(name,kind,visual,price) values('TEST achat','avatar','⭐',20) returning id into c;
 perform public.reward_buy(c);
 if (select balance from public.reward_wallets where user_id=auth.uid())<>before_balance+180 then raise exception 'ÉCHEC : débit';end if;
 blocked:=false;begin perform public.reward_buy(c);exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : achat en double';end if;
 perform public.reward_equip('avatar',c);
 if not exists(select 1 from public.reward_equipment where user_id=auth.uid() and item_id=c) then raise exception 'ÉCHEC : équipement';end if;
 perform public.reward_equip('avatar',null);
 blocked:=false;begin perform public.reward_equip('title',c);exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : mauvais emplacement';end if;
 update public.reward_catalog set price=10000 where id=c;
 delete from public.reward_inventory where user_id=auth.uid() and item_id=c;
 blocked:=false;begin perform public.reward_buy(c);exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : solde insuffisant';end if;
 perform public.reward_mission_action(n,'reserve');
 update public.reward_missions set reserved_until=now()-interval '1 minute' where id=n;
 blocked:=false;begin perform public.reward_mission_action(n,'submit','Trop tard');exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : réservation expirée';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='lecture' limit 1),true);
set local role authenticated;
do $$ declare blocked boolean; c uuid; begin
 if (select count(*) from public.reward_catalog)<15 then raise exception 'ÉCHEC : catalogue invisible';end if;
 if exists(select 1 from public.reward_missions) or exists(select 1 from public.reward_wallets) or exists(select 1 from public.reward_inventory) or exists(select 1 from public.reward_ledger) then raise exception 'ÉCHEC : données admin exposées';end if;
 select id into c from public.reward_catalog limit 1;
 blocked:=false;begin perform public.reward_buy(c);exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : achat employé';end if;
 blocked:=false;begin perform public.reward_equip('avatar',c);exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : équipement employé';end if;
 blocked:=false;begin perform public.reward_mission_action(gen_random_uuid(),'reserve');exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : mission employé';end if;
 blocked:=false;begin insert into public.reward_wallets(user_id,balance) values(auth.uid(),999);exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : écriture directe';end if;
 update public.reward_catalog set price=1;
 if found then raise exception 'ÉCHEC : prix modifiable';end if;
 blocked:=false;
 begin update public.profiles set role='admin' where id=auth.uid();
 exception when insufficient_privilege then blocked:=true;
 when others then if sqlerrm='Only an administrator can change display name, email or role' then blocked:=true;else raise;end if;
 end;
 if not blocked then raise exception 'ÉCHEC : élévation du rôle';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='responsable' limit 1),true);
set local role authenticated;
do $$ declare blocked boolean;begin
 if exists(select 1 from public.reward_missions) then raise exception 'ÉCHEC : missions visibles responsable';end if;
 blocked:=false;begin perform public.reward_mission_action(gen_random_uuid(),'approve');exception when others then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : validation responsable';end if;
end $$;
set local role anon;
do $$ declare blocked boolean;begin
 blocked:=false;begin perform * from public.reward_catalog;exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : catalogue anonyme';end if;
 blocked:=false;begin perform public.reward_buy(gen_random_uuid());exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'ÉCHEC : RPC anonyme';end if;
end $$;
rollback;
select 'PASS : parcours admin, doubles opérations, solde, expiration, lecture employé, responsable, anonyme. Aucun enregistrement de test conservé.' as result;

