(()=>{'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={avatar:'Avatars',frame:'Cadres',accessory:'Accessoires',title:'Titres',theme:'Thèmes'};
const labels={open:'Disponible',reserved:'Réservée',submitted:'À valider',approved:'Validée',cancelled:'Annulée'};
const templates=[['Rangement de la réserve','Réorganiser la zone indiquée. Vérifier que les passages restent dégagés et que chaque produit est à sa place.',20],['Mise en ordre du rayon','Effectuer le facing de la zone indiquée et signaler les emplacements vides.',20],['Passage de relais','Rédiger les informations utiles pour le prochain service et signaler les tâches restantes.',15]];
let db,user,admin=false,tab='shop',category='',filter='active',catalog=[],missions=[],inventory=[],equipment=[],ledger=[],people=[],balance=0,busy=false,formAction=null;
const date=s=>s?new Date(s).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'}):'Sans échéance';
const name=id=>people.find(x=>x.id===id)?.display_name||'Administrateur';
const action=(a,id,label,primary=false,disabled=false)=>`<button data-action="${a}" data-id="${esc(id)}" class="${primary?'primary':''}" ${disabled?'disabled':''}>${esc(label)}</button>`;
function message(t,error=false){$('message').textContent=t;$('message').className=error?'error':'success'}
function check(r){if(r.error)throw r.error;return r.data||[]}
async function load(){
 const requests=[db.from('reward_catalog').select('*').order('price'),db.from('reward_equipment').select('*')];
 if(admin)requests.push(db.from('reward_missions').select('*').order('created_at',{ascending:false}),db.from('reward_inventory').select('*').eq('user_id',user.id),db.from('reward_wallets').select('balance').eq('user_id',user.id),db.from('reward_ledger').select('*').order('created_at',{ascending:false}),db.from('profiles').select('id,display_name'));
 const r=(await Promise.all(requests)).map(check);[catalog,equipment]=r;
 if(admin){[missions,inventory]=[r[2],r[3]];balance=r[4][0]?.balance||0;ledger=r[5];people=r[6];$('balance').textContent=balance}
 render();window.dispatchEvent(new Event('netto:rewards'));
}
function render(){
 const tabs=admin?{missions:'Missions',review:'À valider',shop:'Boutique',collection:'Ma collection',history:'Historique',ranking:'Classement',manage:'Gestion boutique'}:{shop:'Aperçu de la boutique'};
 $('tabs').innerHTML=Object.entries(tabs).map(([k,v])=>`<button data-tab="${k}" ${k===tab?'aria-current="page"':''}>${v}${k==='review'?' · '+missions.filter(m=>m.status==='submitted').length:''}</button>`).join('');
 if(tab==='missions'||tab==='review')renderMissions();else if(tab==='history')renderHistory();else if(tab==='ranking')renderRanking();else renderShop();
}
function renderMissions(){
 const review=tab==='review';let rows=missions.filter(m=>review?m.status==='submitted':filter==='all'||(filter==='active'?['open','reserved'].includes(m.status):m.status===filter));
 $('content').innerHTML=`<div class="row toolbar"><h2>${review?'Travail à vérifier':'Missions du magasin'}</h2>${!review?'<div class="actions"><select id="missionFilter" aria-label="Filtrer les missions"><option value="active">En cours et disponibles</option><option value="all">Toutes les missions</option><option value="approved">Validées</option><option value="cancelled">Annulées</option></select>'+action('new','','Créer une mission',true)+'</div>':''}</div><div class="grid">${rows.map(m=>{
 const expired=m.deadline&&new Date(m.deadline)<=new Date(),released=m.status==='reserved'&&new Date(m.reserved_until)<=new Date();
 let buttons='';if(m.status==='open'||released)buttons=action('reserve',m.id,'Réserver · 1 h',true,!!expired)+action('edit',m.id,'Modifier',false,released)+action('cancel',m.id,'Annuler');
 if(m.status==='reserved'&&!released)buttons=(m.assigned_to===user.id?action('submit',m.id,'Travail terminé',true):'')+action('release',m.id,'Libérer')+action('cancel',m.id,'Annuler');
 if(m.status==='submitted')buttons=action('approve',m.id,'Valider · +'+m.points+' jetons',true)+action('reject',m.id,'À corriger');
 return `<article class="card"><div class="row"><span class="tag">${expired&&m.status==='open'?'Expirée':released?'Réservation expirée':labels[m.status]}</span><span class="points">+${m.points} jetons</span></div><h3>${esc(m.title)}</h3><p>${esc(m.instructions)}</p><div class="meta">Échéance : ${date(m.deadline)}</div>${m.assigned_to?`<div class="meta">${esc(name(m.assigned_to))}${m.reserved_until?' · jusqu’au '+date(m.reserved_until):''}</div>`:''}${m.proof?`<p><strong>Compte rendu</strong><br>${esc(m.proof)}</p>`:''}${m.review_note?`<p><strong>Retour du responsable</strong><br>${esc(m.review_note)}</p>`:''}<div class="actions">${buttons}${action('duplicate',m.id,'Dupliquer')}</div></article>`;
 }).join('')||'<div class="empty">'+(review?'Aucune mission en attente de validation.':'Aucune mission ici. Crée un premier défi pour commencer.')+'</div>'}</div>`;
 if($('missionFilter')){$('missionFilter').value=filter;$('missionFilter').onchange=e=>{filter=e.target.value;renderMissions()}}
}
function preview(c){const color=/^#[0-9a-f]{6}$/i.test(c.visual)?c.visual:'#ea580c';return `<div class="preview">${c.kind==='frame'?`<span class="frame" style="--item-color:${color}">N</span>`:c.kind==='theme'?`<span class="theme" style="--item-color:${color}">Netto</span>`:c.kind==='title'?`<span class="titleReward">${esc(c.visual)}</span>`:`<span class="glyph">${esc(c.visual)}</span>`}</div>`}
function renderShop(){
 const manage=tab==='manage',owned=tab==='collection';let rows=catalog.filter(c=>(manage||c.active||owned&&inventory.some(i=>i.item_id===c.id))&&(!category||c.kind===category)&&(!owned||inventory.some(i=>i.item_id===c.id)));
 $('content').innerHTML=`<div class="row toolbar"><h2>${manage?'Gérer les récompenses':owned?'Ma collection':'Choisis ton prochain objectif'}</h2><div class="filters"><select id="category" aria-label="Catégorie"><option value="">Toutes les catégories</option>${Object.entries(kinds).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select>${manage?action('newItem','','Ajouter un objet',true):''}</div></div><div class="grid">${rows.map(c=>{
 const has=inventory.some(i=>i.item_id===c.id),equipped=equipment.some(e=>e.user_id===user.id&&e.item_id===c.id);
 let buttons=admin?(has?action(equipped?'unequip':'equip',c.id,equipped?'Retirer':'Équiper',!equipped):action('buy',c.id,'Ajouter à ma collection',true)):'';
 if(manage)buttons=action('editItem',c.id,'Modifier')+action('toggleItem',c.id,c.active?'Retirer de la vente':'Remettre en vente');
 return `<article class="card">${preview(c)}<div class="row"><span class="meta">${kinds[c.kind]}</span><span class="points">${c.price} jetons</span></div><h3>${esc(c.name)}</h3>${equipped?'<span class="tag">Équipé</span>':has?'<span class="tag">Dans ma collection</span>':''}${!c.active?'<span class="tag">Hors boutique</span>':''}<div class="actions">${buttons}</div></article>`;
 }).join('')||'<div class="empty">'+(owned?'Ta collection commence avec ton premier achat.':'Aucun objet dans cette catégorie.')+'</div>'}</div>`;
 $('category').value=category;$('category').onchange=e=>{category=e.target.value;renderShop()};
}
function renderHistory(){const own=ledger.filter(l=>l.user_id===user.id);$('content').innerHTML='<h2 class="toolbar">Mes gains et achats</h2><div class="list">'+(own.map(l=>`<article class="entry"><div><strong>${esc(l.description)}</strong><small>${date(l.created_at)} · ${l.amount>0?'Mission validée':'Achat boutique'}</small></div><strong class="${l.amount>0?'positive':'negative'}">${l.amount>0?'+':''}${l.amount} jetons</strong></article>`).join('')||'<div class="empty">Les validations et achats apparaîtront ici.</div>')+'</div>'}
function renderRanking(){const month=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit'}),key=month.format(new Date()),scores={};ledger.filter(l=>l.amount>0&&month.format(new Date(l.created_at))===key).forEach(l=>scores[l.user_id]=(scores[l.user_id]||0)+l.amount);$('content').innerHTML='<h2>Classement du mois</h2><p class="toolbar">Jetons gagnés en '+new Date().toLocaleDateString('fr-FR',{month:'long',year:'numeric',timeZone:'Europe/Paris'})+'. Les achats ne diminuent pas le score. Aperçu réservé à l’admin.</p><div class="list">'+(Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([id,n],i)=>`<article class="entry"><strong>${i+1}. ${esc(name(id))}</strong><span class="points">${n} jetons gagnés</span></article>`).join('')||'<div class="empty">Le classement commencera avec la première mission validée.</div>')+'</div>'}
function openForm(title,fields,submit,fn){$('modalTitle').textContent=title;$('fields').innerHTML=fields;$('saveModal').textContent=submit;$('formError').textContent='';formAction=fn;$('modal').showModal()}
function input(name,label,value='',type='text',attrs=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`}
function missionForm(m,duplicate=false){const initial=m||{title:'',instructions:'',points:20};let local='';if(m?.deadline&&!duplicate){const d=new Date(m.deadline);local=new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
 openForm(m&&!duplicate?'Modifier la mission':'Créer une mission',(!m?'<label>Partir d’un modèle<select id="template"><option value="">Mission personnalisée</option>'+templates.map((t,i)=>`<option value="${i}">${esc(t[0])}</option>`).join('')+'</select></label>':'')+input('title','Titre',initial.title,'text','required maxlength="120"')+`<label>Travail attendu et critères de validation<textarea name="instructions" required maxlength="2000">${esc(initial.instructions)}</textarea></label>`+input('points','Récompense en jetons',initial.points,'number','required min="1" max="1000" step="1"')+input('deadline','Échéance (facultative)',local,'datetime-local'),m&&!duplicate?'Enregistrer':'Créer la mission',async f=>{const data={title:f.get('title').trim(),instructions:f.get('instructions').trim(),points:Number(f.get('points')),deadline:f.get('deadline')?new Date(f.get('deadline')).toISOString():null};if(data.deadline&&new Date(data.deadline)<=new Date())throw Error('Choisis une échéance future.');if(!data.title||!data.instructions)throw Error('Complète le titre et les critères.');if(m&&!duplicate){const r=check(await db.from('reward_missions').update(data).eq('id',m.id).eq('status','open').select('id'));if(!r.length)throw Error('La mission a changé. Actualise la page.')}else check(await db.from('reward_missions').insert({...data,created_by:user.id}));});
 if($('template'))$('template').onchange=e=>{const t=templates[Number(e.target.value)];if(e.target.value!==''&&t){$('editor').elements.title.value=t[0];$('editor').elements.instructions.value=t[1];$('editor').elements.points.value=t[2]}};
}
function itemForm(c){openForm(c?'Modifier l’objet':'Ajouter un objet',input('name','Nom',c?.name||'','text','required maxlength="70"')+`<label>Catégorie<select name="kind" ${c?'disabled':''}>${Object.entries(kinds).map(([k,v])=>`<option value="${k}" ${c?.kind===k?'selected':''}>${v}</option>`).join('')}</select></label>`+input('visual','Emoji, titre ou couleur hexadécimale (#2563eb)',c?.visual||'⭐','text','required maxlength="70"')+input('price','Prix en jetons',c?.price||20,'number','required min="1" max="10000" step="1"')+'<p>Une modification visuelle s’applique aussi aux objets déjà équipés. Les achats passés conservent leur montant.</p>','Enregistrer',async f=>{const kind=c?.kind||f.get('kind'),visual=f.get('visual').trim(),data={name:f.get('name').trim(),kind,visual,price:Number(f.get('price'))};if(!data.name||!visual)throw Error('Complète le nom et le visuel.');if(['theme','frame'].includes(kind)&&!/^#[0-9a-f]{6}$/i.test(visual))throw Error('Utilise une couleur au format #2563eb.');check(await (c?db.from('reward_catalog').update(data).eq('id',c.id):db.from('reward_catalog').insert(data)));})}
function confirmAction(title,text,label,fn){openForm(title,`<p>${esc(text)}</p>`,label,fn)}
async function click(a,id){if(!admin)return;const m=missions.find(x=>x.id===id),c=catalog.find(x=>x.id===id);const rpc=(act,note='')=>db.rpc('reward_mission_action',{p_id:id,p_action:act,p_note:note}).then(check);
 if(a==='new'||a==='edit'||a==='duplicate'){missionForm(m,a==='duplicate');return}if(a==='newItem'||a==='editItem'){itemForm(c);return}
 if(a==='submit'||a==='reject'){openForm(a==='submit'?'Terminer la mission':'Demander une correction',`<p>${esc(m.title)}</p><label>${a==='submit'?'Compte rendu du travail réalisé':'Correction attendue'}<textarea name="note" required minlength="3" maxlength="${a==='submit'?2000:1000}"></textarea></label>`,a==='submit'?'Envoyer pour validation':'Rouvrir la mission',f=>rpc(a,f.get('note')));return}
 if(a==='approve'){confirmAction('Valider la mission',`${m.title} : attribuer ${m.points} jetons à ${name(m.assigned_to)} ? Pendant le pilote, l’admin peut valider son propre essai.`,'Valider',()=>rpc(a));return}
 if(a==='cancel'||a==='release'){confirmAction(a==='cancel'?'Annuler la mission':'Libérer la mission',m.title,a==='cancel'?'Annuler la mission':'Libérer',()=>rpc(a));return}
 if(a==='buy'){confirmAction('Ajouter à la collection',`${c.name} sera ajouté à ta collection administrateur sans utiliser de jetons.`,'Ajouter',()=>db.rpc('reward_buy',{p_item:id}).then(check));return}
 if(a==='toggleItem'){confirmAction(c.active?'Retirer de la vente':'Remettre en vente',c.active?'Les propriétaires conserveront cet objet et pourront toujours l’équiper.':c.name,'Confirmer',()=>db.from('reward_catalog').update({active:!c.active}).eq('id',id).then(check));return}
 if(busy)return;busy=true;try{if(a==='reserve')await rpc(a);else if(a==='equip'||a==='unequip')check(await db.rpc('reward_equip',{p_kind:c.kind,p_item:a==='equip'?id:null}));await load();message('Modification enregistrée.')}catch(e){message(e.message||'Opération impossible.',true)}finally{busy=false}
}
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;category='';render()}};
$('content').onclick=e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)click(b.dataset.action,b.dataset.id).catch(err=>message(err.message,true))};
$('closeModal').onclick=$('cancelModal').onclick=()=>$('modal').close();
$('editor').onsubmit=async e=>{e.preventDefault();if(busy||!formAction)return;busy=true;$('saveModal').disabled=true;$('formError').textContent='';try{await formAction(new FormData($('editor')));$('modal').close();message('Enregistré.');await load()}catch(err){if($('modal').open)$('formError').textContent=err.message||'Enregistrement impossible.';else message('Action enregistrée, mais actualisation impossible. Recharge la page.',true)}finally{busy=false;$('saveModal').disabled=false}};
async function boot(){try{if(!window.supabase)throw Error('Connexion indisponible. Recharge la page.');db=supabase.createClient('https://gioxrpaiwogqqtakjpnv.supabase.co','sb_publishable_nJPMS-Z_20ng1aMJmufbmg_gWFFndrC');const r=await db.auth.getUser();if(r.error||!r.data.user){location.replace('index.html');return}user=r.data.user;const profiles=check(await db.from('profiles').select('role').eq('id',user.id));if(!profiles.length)throw Error('Compte introuvable.');admin=profiles[0].role==='admin';if(!admin){location.replace('home.html');return}tab='missions';$('wallet').hidden=false;$('tabs').hidden=false;$('intro').textContent='Des missions utiles et une collection entièrement personnalisable.';$('notice').hidden=false;$('notice').textContent='Espace administrateur : le catalogue est utilisable sans restriction de jetons. Les réglages d’apparence sont également centralisés dans Mon profil.';await load();}catch(e){$('content').innerHTML='<div class="empty">Impossible de charger cet espace. <button id="retry">Réessayer</button></div>';$('retry').onclick=boot;message(e.message||'Connexion impossible.',true)}}
boot();window.addEventListener('focus',()=>{if(user&&!$('modal').open&&!busy)load().catch(e=>message('Actualisation impossible : '+e.message,true))});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();

